### ISSUE TITLE
How do i change tab text color?

### ISSUE THREAD

**Issue by Mohammad-Taqi** [vaibhav1929/android-navigation-bar#3]

**Comment by vaibhav1929** [comment]
Currently, it sets the text color automatically based on your bar background, (if it is dark then the text is white otherwise in case of lighter colors it will be black).
I will add the function to set the color manually.

**Comment by Mohammad-Taqi** [comment]
oky thx... and how do I clear badge from tab on click?

**Comment by vaibhav1929** [comment]
I am updating the library. so you will get that function within 1 hour. :)

To clear the badge, you can use `removeBadge(int tabIndex)` method using Flarebar object. just send the index of tab in argument, call this method in onClick.

I recommend to check <b> available methods </b> in readme.

**Comment by Mohammad-Taqi** [comment]
Oky
